"""create_activity_log_table

Revision ID: 513e86b08ba6
Revises: 037300e67e18
Create Date: 2023-02-07 03:57:26.524947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513e86b08ba6'
down_revision = '037300e67e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=50), nullable=True),
    sa.Column('log_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.String(length=255), nullable=True),
    sa.Column('causer_id', sa.Integer(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_log')
    # ### end Alembic commands ###
